# Generated by Django 3.2.9 on 2021-12-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musician',
            new_name='Tour',
        ),
    ]
