# Generated by Django 3.2.9 on 2021-12-14 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_musician_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
