# Generated by Django 4.0.1 on 2022-01-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tour_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='preferred_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='preferred_time',
            field=models.CharField(choices=[('13:30', '13:30'), ('15:30', '15:30')], max_length=5),
        ),
    ]
