# Generated by Django 4.0.1 on 2022-02-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_preferred_date_alter_tour_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6),
        ),
    ]
