# Generated by Django 4.0.1 on 2022-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6, null=True),
        ),
    ]
