# Generated by Django 4.0.1 on 2022-02-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default='15', max_digits=6),
        ),
    ]
