# Generated by Django 4.0.1 on 2022-02-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_alter_tour_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
    ]
