# Generated by Django 3.2.9 on 2021-12-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(
                    blank=True, max_length=254, null=True)),
                ('artist_statement', models.TextField()),
                ('image_url', models.URLField(
                    blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('instagram_url', models.URLField(
                    blank=True, max_length=1024, null=True)),
                ('website_url', models.URLField(
                    blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Captures',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('sku', models.CharField(
                    blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(
                    blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(
                    blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(
                    blank=True, null=True, upload_to='')),
                ('artist', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='captures.artist')),
            ],
        ),
    ]
