# Generated by Django 3.2.9 on 2021-12-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_auto_20211206_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Captures',
            new_name='Capture',
        ),
        migrations.AlterModelOptions(
            name='capture',
            options={'verbose_name_plural': 'Captures'},
        ),
    ]
