# Generated by Django 3.2.9 on 2021-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0003_auto_20211212_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='rating',
        ),
        migrations.AddField(
            model_name='capture',
            name='has_option',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
